export const ActionTypes={
    SET_PRODUCTS : "SET_PRODUCTS",
    LOADING_PRODUCTS :"LOADING_PRODUCTS",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    ADD_BASKET:"ADD_BASKET",
    DELETE_BASKET:"DELETE_BASKET",
    UPDATE_BASKETPRODUCT:"UPDATE_BASKETPRODUCT"
}